### ISSUE TITLE
快捷键及易用性问题

### ISSUE THREAD

**Issue by WinXS** [imlinhanchao/vsc-google-translate#1]
快捷键无法自定义，对于翻译工作者并不友好。且响应速度不够快，翻译内容不能完全显示。
建议一键翻译复制替换（或带上括号并添加文本内容末尾）
Eg："plasteel"  按下快捷键
→ "plasteel（玻璃钢）"或 "玻璃钢"

**Comment by imlinhanchao** [comment]
快捷键的自定义，应该是在VSCode的键盘快捷键设置里面可以设置的，在里面搜索translate，可以找到。翻译替换这个我找时间搞搞吧~

**Comment by imlinhanchao** [comment]
@WinXS 替换功能已经上线啦~
