### ISSUE TITLE
The notifications on the bottom right

### ISSUE THREAD

**Issue by temurih** [imlinhanchao/vsc-google-translate#10]
The notifications at the bottom right, keep popping up when I translate something. I wonder if there is an option to limit those to error only. Meaning, they should not appear if the translation was successful, because you can see it working on your screen. Only if there is an error while translating.

![image](https://user-images.githubusercontent.com/3893769/120939328-d262f880-c6d4-11eb-88eb-1d260c3914c3.png)

**Comment by imlinhanchao** [comment]
OK~I get it. I will add a option.

**Comment by imlinhanchao** [comment]
You can update to 1.2.2 and checked option `google-translate.noticeOnlyError`.

**Comment by temurih** [comment]
It works like a charm! Thank you!
