### ISSUE TITLE
翻译替换失效

### ISSUE THREAD

**Issue by yedajiang44** [imlinhanchao/vsc-google-translate#12]
1.2+版本的翻译替换全部失效

**Comment by imlinhanchao** [comment]
實測正常，請問有錯誤信息嗎？

**Comment by yedajiang44** [comment]
难道是我键盘问题？？？
这是我的快捷键配置
![image](https://user-images.githubusercontent.com/25813145/121987854-dfb26e00-cdcb-11eb-9d6f-cb77c004de6c.png)

这是我使用快捷键后的状态

![image](https://user-images.githubusercontent.com/25813145/121987966-11c3d000-cdcc-11eb-84f5-385f94f06ea3.png)

**Comment by imlinhanchao** [comment]
看你的右下角，你設定為僅對英文翻譯成中文了，應該點擊 `en` ，設定為 `auto` 。這樣中文才會被翻譯為 英文。

**Comment by yedajiang44** [comment]
还真是！可能是同步配置，指不定是哪台机器被点过同步过来了，感谢~
