### ISSUE TITLE
xsel clipboard in WSL2 Linux

### ISSUE THREAD

**Issue by JeromeBenedetti** [imlinhanchao/vsc-google-translate#13]
Using the extension on WSL2 makes it impossible to copy to clipboard :
```bash
xsel: Can't open display: (null)
: Inappropriate ioctl for device
```

### Suggest :
Maybe create a new setting like `Clipboard Manager` that defaults to `xsel` but that we can set to `clip.exe` for WSL users.

**Comment by imlinhanchao** [comment]
Are you use VSCode in WSL2 ?

**Comment by JeromeBenedetti** [comment]
Yes, with Ubuntu in WSL2

**Comment by imlinhanchao** [comment]
@JeromeBenedetti The issue was fixed. You can update to 1.2.3 to check it.

**Comment by JeromeBenedetti** [comment]
Right ! Thank you for your reactivity, and thanks fo this cool extension !
