### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by KahnDepot** [imlinhanchao/vsc-google-translate#14]
I tried to translate Chinese into English, but the result is still Chinese。
Like below：
![image](https://user-images.githubusercontent.com/81478335/124549553-e29bfe00-de61-11eb-9eeb-0de69af3c211.png)
Or switch it, the translation result is still in Chinese：
![image](https://user-images.githubusercontent.com/81478335/124549659-0eb77f00-de62-11eb-9f7d-844f14d87152.png)

**Comment by imlinhanchao** [comment]
click `python` and then set to `auto`.

**Comment by KahnDepot** [comment]
Responding quickly, this is indeed effective. Thank you very much
