### ISSUE TITLE
Error message: 'The language 'json' is not supported'.

### ISSUE THREAD

**Issue by Kingzhoudk** [imlinhanchao/vsc-google-translate#17]
![图片](https://user-images.githubusercontent.com/35418703/133718520-9194d545-9570-4be4-9c5a-9f22a1c5856c.png)

**Comment by imlinhanchao** [comment]
please give me your extension setting. thanks.

**Comment by imlinhanchao** [comment]
maybe it's the same issue: https://github.com/imlinhanchao/vsc-google-translate/issues/14
