### ISSUE TITLE
Translate failed, Error message: 'The language 'WXML' is not supported'. Please post an issues for me.

### ISSUE THREAD

**Issue by aimey-a** [imlinhanchao/vsc-google-translate#19]
![image](https://user-images.githubusercontent.com/74888711/134614250-c88c76ec-7fa2-4b05-985e-8940387991d7.png)
![image](https://user-images.githubusercontent.com/74888711/134614328-b0e4278c-0d84-4fa1-a270-d2d9f408f13f.png)

**Comment by imlinhanchao** [comment]
点击 → 左边的空白按钮，设置成为 auto

**Comment by aimey-a** [comment]
没有可以设置为auto的按钮

**Comment by imlinhanchao** [comment]
那就应该是那个 `wxml`

**Comment by aimey-a** [comment]
![image](https://user-images.githubusercontent.com/74888711/134614903-cf7250e1-85cc-48fa-89e7-585091894739.png)
换成vue 也不行

**Comment by aimey-a** [comment]
![image](https://user-images.githubusercontent.com/74888711/134614998-830b445c-c5fa-4373-a118-4e95a56e4de0.png)
HTML也一样

**Comment by imlinhanchao** [comment]
正常应该有个 自动按钮在这里，你之前有修改过吗？

![image](https://user-images.githubusercontent.com/1502581/134615085-641cdf04-9d17-4074-a115-ef29fb577125.png)

**Comment by aimey-a** [comment]
好的，谢谢

**Comment by imlinhanchao** [comment]
解决了？

**Comment by aimey-a** [comment]
嗯，解决了，我之前是安装的老版本，前几天提示更新就这样了。
