### ISSUE TITLE
et-EE language

### ISSUE THREAD

**Issue by KalleSoft** [imlinhanchao/vsc-google-translate#20]
![image](https://user-images.githubusercontent.com/65413197/137087468-00d09dbe-4166-470c-a176-1c70a80ba529.png)

**Comment by imlinhanchao** [comment]
what's your setting?

**Comment by KalleSoft** [comment]
It's working now, but only one way en->et (Ctrl+Alt+T) 
actually a tooltip shows the correct word
![image](https://user-images.githubusercontent.com/65413197/137096172-07f9c1a5-ced5-474a-af37-27ef5982c6d5.png)
