### ISSUE TITLE
不能在markdown的preview界面使用吗？

### ISSUE THREAD

**Issue by gtianw** [imlinhanchao/vsc-google-translate#21]
markdown原始文件有太多额外的符号，严重影响了翻译效果，要是能在preview界面使用就好了

**Comment by imlinhanchao** [comment]
OK~我想想看怎么处理。

**Comment by gtianw** [comment]
没想到这么快就回复了，还有插件介绍页也不能使用

**Comment by imlinhanchao** [comment]
插件介绍页是指什么？

**Comment by imlinhanchao** [comment]
哦哦~我知道了。我也看看

**Comment by imlinhanchao** [comment]
markdown preview 和 插件介绍页都是 webview，经过确认，目前 vscode 没有开放 API 可以对其内容操作或识别。所以你的需求无法实现。

**Comment by gtianw** [comment]
好的，感谢大佬！
1、插件页已不是问题，直接在Chrome浏览器上打开，使用浏览器插件即可；
2、看来接下来得研究下怎么用Chrome打开markdown了:smile:

**Comment by imlinhanchao** [comment]
使用 Markdown PDF 扩展可以把 Markdown 导出成为 HTML。然后再用浏览器打开即可。
