### ISSUE TITLE
Translate failed，connect ECONNREFUSED

### ISSUE THREAD

**Issue by Esansiy** [imlinhanchao/vsc-google-translate#24]
Translate failed, Error message: 'connect ECONNREFUSED 47.240.3.121:443'.

**Comment by imlinhanchao** [comment]
目前仅能通过 Google Translate 镜像或设置代理解决。

设置代理方式，按下 `Ctrl + ,` 打开设置。首先将 `google-translate.serverDomain` 的值修改为 `https://translate.google.com.hk` 或 `https://translate.google.com` ，然后再修改 `http.proxy` 值为你的本地代理软件的 HTTP 代理。比如 `http://127.0.0.1:1089`。
