### ISSUE TITLE
Translate failed, Error message: 'Response code 302'

### ISSUE THREAD

**Issue by BlackWyJiang** [imlinhanchao/vsc-google-translate#26]
版本：1.2.7
报错信息：

- 使用translate.google.com.hk域名

`Translate failed, Error message: 'Response code 302 (Found) Url: https://translate.google.com.hk/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=7603153056713606254&bl=boq_translate-webserver_20221030.01_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=4669&rt=c'. Please post an issues for me.`

- 使用自带域名
`Translate failed, Error message: 'Response code 302 (Found) Url: https://t.hancel.org/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-2814932325942997099&bl=boq_translate-webserver_20221030.01_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=5092&rt=c'. Please post an issues for me.`

**Comment by imlinhanchao** [comment]
现在只能代理访问了，修改为 translate.google.com 然后设置 `http.proxy`
