### ISSUE TITLE
Translate failed, please check your network.

### ISSUE THREAD

**Issue by czd890** [imlinhanchao/vsc-google-translate#3]
本地网络没有问题，浏览器打开https://translate.google.cn/,响应速度很快。

**Comment by imlinhanchao** [comment]
请协助提供翻译的文本。

**Comment by imlinhanchao** [comment]
刚刚更新了一个版本，加入内部错误的详细信息，请再帮忙试试并提供错误资讯。

**Comment by czd890** [comment]
Translate failed, Error message: "The "listener" argument must be of type Function. Received type object". Please post an issues for me.

**Comment by imlinhanchao** [comment]
em，这个错误信息还真是奇怪，唯一的`listener`参数就只有`https`模块的 Response 事件监听。但是确确实实是传入的函数没错。你的 VSCode 版本是多少，是最新版吗？

**Comment by imlinhanchao** [comment]
我似乎找到问题了，似乎是Node 8 与 Node 10 差异的兼容性 Bug。但我这边没有办法验证。你可以帮忙试试吗？
[google-translate-0.0.9.zip](https://github.com/imlinhanchao/vsc-google-translate/files/3845543/google-translate-0.0.9.zip)
先卸载商店安装的插件，然后下载这个插件安装包。解压后选中左上角 `...` 从 VSIX 安装。看看是否还有问题。
![image](https://user-images.githubusercontent.com/1502581/68841868-5bd06580-0700-11ea-9959-05df44ab5b64.png)

**Comment by czd890** [comment]
vs version info:
``` shell
版本: 1.40.1 (user setup)
提交: 8795a9889db74563ddd43eb0a897a2384129a619
日期: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.14393
```

![image](https://user-images.githubusercontent.com/4011549/68915518-64c34480-079d-11ea-8e26-39a7491b3d2d.png)

**Comment by imlinhanchao** [comment]
好的，了解了，1.0.8开始为了减少包大小，没有用 request 库区做网络请求，改成用 https 自己实现。这样看似乎容易有兼容性问题。

**Comment by czd890** [comment]
NB，你这个响应速度吊炸天了！

**Comment by imlinhanchao** [comment]
哈哈，因为日常摸鱼刷 GitHub，我晚上换一个轻量级的请求库再打包一版给你试试。

**Comment by imlinhanchao** [comment]
[google-translate-0.0.9.zip](https://github.com/imlinhanchao/vsc-google-translate/files/3853757/google-translate-0.0.9.zip)
改好了，换了got的请求库，试试这个怎么样？

**Comment by imlinhanchao** [comment]
修复问题的版本 1.0.10 已上线，可以卸载调试版本再上扩展商店安装最新版本。
