### ISSUE TITLE
翻译域名https://translate.amz.wang，报302

### ISSUE THREAD

**Issue by sicaifang** [imlinhanchao/vsc-google-translate#39]
![image](https://user-images.githubusercontent.com/21259427/232958922-6a5f0b34-9916-4c1a-a26a-81bb2847274d.png)

Translate failed, Error message: 'Response code 302 (Found) Url: https://translate.amz.wang/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-5253567319347899952&bl=boq_translate-webserver_20230417.08_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=6510&rt=c'. Please post an issues for me.

**Comment by imlinhanchao** [comment]
参考此 issue 修改：https://github.com/imlinhanchao/vsc-google-translate/issues/34
