### ISSUE TITLE
如何修改成支持Chinese (Traditional)

### ISSUE THREAD

**Issue by amigomcu** [imlinhanchao/vsc-google-translate#5]
hi 
如何修改成支持Chinese (Traditional)

**Comment by imlinhanchao** [comment]
春节找时间更新一波，加入设定界面。

**Comment by imlinhanchao** [comment]
> hi
> 如何修改成支持Chinese (Traditional)

此功能已上線，現在可以設置啦。如果VSCode本身使用繁體中文，默認將會是繁體中文：

![image](https://user-images.githubusercontent.com/1502581/73336147-05f56d80-42ac-11ea-9a0c-200af6dc5771.png)
