### ISSUE TITLE
提些建议

### ISSUE THREAD

**Issue by zhw2590582** [imlinhanchao/vsc-google-translate#6]
用了一段时间了，建议添加个复制按钮，每次翻译一串长长的文字后，都要选取一遍长长的翻译结果好麻烦。然后谷歌翻译返回的结果好像都换行了，所以翻译结果可以trim一下。

**Comment by imlinhanchao** [comment]
如果内容本身有换行，翻译结果应该会依照换行。翻译复制的话有对应快捷键，浮动框只能写 Markdown 好像，不太确定是否可以加动作。我试试看。

**Comment by imlinhanchao** [comment]
> 用了一段时间了，建议添加个复制按钮，每次翻译一串长长的文字后，都要选取一遍长长的翻译结果好麻烦。

这边实验悬停框是无法添加其他动作的，如果你是选中后触发 `translates.translates` 指令，那么应该会再左下角有一个按钮，点击可以复制，如果是悬停的，确实就得自行选中。也可以尝试试用 `translates.clipboard` 指令，会把翻译结果直接放在剪贴板。

> 然后谷歌翻译返回的结果好像都换行了，所以翻译结果可以trim一下。

这个现象是怎么样？有没有范例，期望产生什么样的翻译结果？

**Comment by zhw2590582** [comment]
例如这句话：`然后谷歌翻译返回的结果好像都换行了`
然后翻译结果出现在悬停框上，双击全选中，`ctrl + c`进行复制，最后`ctrl + v`粘贴
最终结果是英文后面还带有两个换行符，本来一行的，变成三行了，每次都要手动删除后两行

```
Then the results returned by Google Translate seem to wrap


```
