### ISSUE TITLE
Translate failed, Error message: 'Response code 407 (authenticationrequired)'. 

### ISSUE THREAD

**Issue by CloudClock** [imlinhanchao/vsc-google-translate#7]
Translate failed, Error message: 'Response code 407 (authenticationrequired)'. Please post an issues for me.

**Comment by imlinhanchao** [comment]
This seems to be a client error. It was caused by an agent. Do you have any agent software enabled?

**Comment by imlinhanchao** [comment]
> Translate failed, Error message: 'Response code 407 (authenticationrequired)'. Please post an issues for me.

Is the issue resolved? If it is resolved, will this issue be closed.
请问问题是否已解决，若已解决，此 Issue 将 Close。
