### ISSUE TITLE
Could u help me with this? 

### ISSUE THREAD

**Issue by vashellsing** [imlinhanchao/vsc-google-translate#9]
First of all, thank you for being the only translator that has worked for me. so thank you very much.
I'm someone who uses the replace text feature a lot.

![works](https://user-images.githubusercontent.com/34943631/97634571-f0ac9b80-1a03-11eb-837b-2dab3e76c05b.gif)

But as you will notice, there are times when I need to translate many lines of code without affecting the code, only specific texts, but the extension only translates the first line.

![dontwork](https://user-images.githubusercontent.com/34943631/97635016-ab3c9e00-1a04-11eb-8387-f68a3a495bdc.gif)

if I select all the text, as a single paragraph it works, but sometimes it translates the code that it shouldn't and makes it unusable.

![dontwork2](https://user-images.githubusercontent.com/34943631/97635472-6d8c4500-1a05-11eb-9de5-3fdef2627cf6.gif)

Therefore, I would like to know if there is any possibility of translating several lines of text at the same time, without modifying the code, translating only specific text, I am a newbie and I do not know if I am doing something wrong, or should I do something specific to make it work ,  Thanks a lot

**Comment by imlinhanchao** [comment]
That is a problem. I will fix it this week. Thanks your feedback.

**Comment by imlinhanchao** [comment]
This issue was fixed. You can update to version 1.1.6.

**Comment by vashellsing** [comment]
It works perfectly, thank you very much!!!
